<?php

function getSurname()
{
    $surnames = array(
        "Hoxha",
        "Shehu",
        "Murad",
        "Brahimi",
        "Halili",
        "Shkodra",
        "Prishtina",
        "Hovhannisyan",
        "Khachatryan",
        "Gruber",
        "Bauer",
        "Pichler",
        "Hofer",
        "Brunner",
        "Wolf",
        "Schuster",
        "Jacobs",
        "Dubois",
        "Lambert",
        "Nielsen",
        "Christensen",
        "Joensen",
        "Korhonen",
        "Laine",
        "Heikkinen",
        "Laitinen",
        "Lahtinen",
        "Thomas",
        "Durand",
        "Roux",
        "André",
        "Martinez",
        "Müller",
        "Schneider",
        "Samaras",
        "Papoutsis",
        "Aivaliotis",
        "Koufos",
        "Russo",
        "Giordano",
        "Mariani",
        "Martinelli",
        "De Angelis",
        "Krasniqi",
        "Dijkstra",
        "Bogdanov",
        "Davidov",
        "Kitanovski",
        "Pereira",
        "Marques",
        "Khan",
        "McLaughlin",
        "Narayan",
        "Maharaj",
        "Lavoie",
        "Reyes",
        "Rosario",
        "Vásquez",
        "Vargas",
        "Trevino",
        "Reyes"
    );
        
    $numberNames = count($surnames);
    
    $randomName = rand (0, ($numberNames - 1) );
    
    return $surnames[$randomName];
}


function getRandomSex()
{
    $sex = "";

    $sexIdentity = rand (0, 1);

    if($sexIdentity == 0)
    {
        $sex = 'Female';
    }
    else
    {
        $sex = 'Male';
    }

    return $sex;

}

function getCharacterName ($sex)
{
    if($sex == 'Female')
    {
        
        $femaleNames = array(
        "Bella",
        "Luna",
        "Sadie",
        "Chloe",
        "Zoey",
        "Roxy",
        "Gracie",
        "Ruby",
        "Ellie",
        "Abby",
        "Piper",
        "Sasha",
        "Riley",
        "Izzy",
        "Maya",
        "Cali",
        "Millie",
        "Belle",
        "Harley",
        "Charlie",
        "Willow",
        "Marley",
        "Dakota",
        "Callie",
        "Hazel",
        "Shelby",
        "Jasmine",
        "Ava",
        "Fiona",
        "Sydney",
        "Josie",
        "Cleo",
        "Leia",
        "Delilah",
        "Shadow",
        "Macy",
        "Allie",
        "Bonnie",
        "Lacey",
        "Ashes",
        "Misty",
        "Kiki",
        "Gracie",
        "Lakshmi",
        "Tiara",
        "Twinkle",
        "Charlotte",
        "Ade",
        "Anna",
        "Aletona",
        "Branwyn",
        "Aleena",
        "Arlana",
        "Brienna",
        "Diva",
        "Devona",
        "Elsha",
        "Evelina",
        "Gildas",
        "Ginessa",
        "Gwendolen",
        "Gwenyver",
        "Gwynn",
        "Idelisa",
        "Isolda",
        "Isolde",
        "Jennyver",
        "Keelia",
        "Lavena",
        "Linnette",
        "Lyonesse",
        "Melvina",
        "Morrigan",
        "Muriel",
        "Nareena",
        "Oriana",
        "Rowena",
        "Yseult",
        "Abellona",
        "Anneka",
        "Freya",
        "Gisela",
        "Helga",
        "Katarina",
        "Katryn",
        "Linnea",
        "Lisabet",
        "Monika",
        "Petronilla",
        "Rebekka",
        "Thora",
        "Viveka",
        "Alyssandra",
        "Angelique",
        "Arcene",
        "Aubrianne",
        "Celesse",
        "Cendrillon",
        "Chantay",
        "Charmain",
        "Aldona",
        "Allaryce",
        "Delmira",
        "Gabriele",
        "Galiana",
        "Genoveva",
        "Geralynn",
        "Grisella",
        "Heida",
        "Idaia",
        "Isana",
        "Isolda",
        "Johannah",
        "Karlene",
        "Katharina",
        "Rolanda",
        "Rudella",
        "Vanda",
        "Frederica",
        "Juliana",
        "Kendra",
        "Maida",
        "Odelyna",
        "Rowena",
        "Sunniva",
        "Aleezah",
        "Ashira",
        "Atarah",
        "Azelia",
        "Daliyah",
        "Dalya",
        "Darissa",
        "Divsha",
        "Eleora",
        "Evacska",
        "Galenka",
        "Gavriela",
        "Genisia",
        "Katriel",
        "Keiyn",
        "Ksena",
        "Lemuela",
        "Lizbeth",
        "Madalyn",
        "Maribel",
        "Marisha",
        "Matana",
        "Meira",
        "Myriam",
        "Nechama",
        "Reveka",
        "Rinnah"
        );
        
        $numberNames = count($femaleNames);
        
        $randomName = rand (0, ($numberNames - 1) );
        
        return $femaleNames[$randomName];
        
    }
    else
    {
        
        $maleNames = array(
        "Max",
        "Charlie",
        "Cooper",
        "Rocky",
        "Duke",
        "Tucker",
        "Bentley",
        "Milo",
        "Riley",
        "Murphy",
        "Jackson",
        "Gus",
        "Oscar",
        "Baxter",
        "Ollie",
        "Diesel",
        "Bruno",
        "Bandit",
        "Moose",
        "Finn",
        "Marley",
        "Loki",
        "Brody",
        "Jasper",
        "Ace",
        "Shadow",
        "Rocco",
        "Apollo",
        "Roscoe",
        "Scout",
        "Rex",
        "Tyson",
        "Rusty",
        "Otis",
        "Koda",
        "Gunner",
        "Hunter",
        "Joey",
        "Boomer",
        "Ziggy",
        "Copper",
        "Frankie",
        "Benny",
        "Brutus",
        "Ranger",
        "Chase",
        "Chance",
        "Kobe",
        "Chewy",
        "Benji",
        "Rufus",
        "Cash",
        "Baldulf",
        "Balen",
        "Balin",
        "Bertram",
        "Bran",
        "Bryan",
        "Cadwallon",
        "Caerleon",
        "Calibom",
        "Camlann",
        "Carrado",
        "Dagonet",
        "Dinadan",
        "Dristan",
        "Drudwyn",
        "Evalac",
        "Florence",
        "Gahariet",
        "Gaheris",
        "Galahad",
        "Galahault",
        "Garreth",
        "Gawain",
        "Gurgalan",
        "Hellekin",
        "Houdain",
        "Isdemus",
        "Kaherdin",
        "Kanelinqes",
        "Lamorak",
        "Laudegrance",
        "Llacheu",
        "Lohengrin",
        "Lucan",
        "Maheloas",
        "Melechan",
        "Melyon",
        "Mordrain",
        "Pellanor",
        "Pellinore",
        "Percyvelle",
        "Taliesin",
        "Tristan",
        "Tristram",
        "Aksel",
        "Balder",
        "Bjarne",
        "Bjorn",
        "Diederik",
        "Edletd",
        "Aldwyn",
        "Barton",
        "Bertram",
        "Bordan",
        "Cerdic",
        "Creighton",
        "Daegal",
        "Devyn",
        "Durwin",
        "Durwyn",
        "Erol",
        "Gaderian",
        "Godric",
        "Ingram",
        "Ivor",
        "Kendrick",
        "Kenric",
        "Kingsley",
        "Leanian",
        "Lucan",
        "Odin",
        "Ormod",
        "Rowan",
        "Ryce",
        "Selwyn",
        "Sherwyn",
        "Tamar",
        "Tolan",
        "Adalric",
        "Adalwine",
        "Adalwolf",
        "Alphonso",
        "Amaud",
        "Darek",
        "Diederich",
        "Eberhardt",
        "Edwyn",
        "Erich",
        "Frantz",
        "Ghislain",
        "Gregor",
        "Johann",
        "Kuhlbert",
        "Meilyr",
        "Mihangel",
        "Sawyl",
        "Steffan",
        "Talfryn",
        "Tewdwr",
        "Trefor",
        "Tristram",
        "Tudor",
        "Vaughn",
        "Jonathan",
        "Matthias",
        "Micah",
        "Nathanel",
        "Samuel",
        "Gael",
        "Gallagher",
        "Gillean",
        "Greagoir",
        "Hanraoi",
        "Harkin",
        "Jarlath",
        "Kane",
        "Keagan",
        "Kellach",
        "Kerwyn",
        "Killdaire",
        "Kyrell",
        "Korrigan",
        "Laoghaire",
        "Monohan",
        "Peyton",
        "Riddock",
        "Rowan",
        "Ryley"
        );
        
        $numberNames = count($maleNames);
        
        $randomName = rand (0, ($numberNames - 1) );
        
        return $maleNames[$randomName];
    }
}


function getRandomName ($sex)
{
    $name = "";
    $theSex;

    if($sex == 'Male')
    {
        $theSex = 'Male';
    }
    else if($sex == 'Female')
    {
        $theSex = 'Female';
    }
    else
    {
        $theSex = getRandomSex();

    }

    $name = getCharacterName ($theSex);

    return $name;
}




?>